# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='test@aol.com', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='temp', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='temp', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='temp', max_length=128),
            preserve_default=False,
        ),
    ]
